--Average Engagement Score by Department

SELECT BUSINESSUNIT, ROUND(AVG(ENGAGEMENT_SCORE),2) as AVGSCORE FROM (SELECT E1.EMPID,E1.BUSINESSUNIT, E2.ENGAGEMENT_SCORE FROM EMPLOYEES E1 INNER JOIN EMPLOYEE_ENGAGEMENT_SURVEY E2 ON E1.EMPID=E2.EMPLOYEE_ID)
GROUP BY BUSINESSUNIT

--Impact of Training on Employee Performance

SELECT E1.EMPLOYEE_ID,E1.TRAINING_OUTCOME,E2.FIRSTNAME, E2.PERFORMANCESCORE FROM TRAINING_DEV E1 JOIN EMPLOYEES E2 ON E1.EMPLOYEE_ID=E2.EMPID

-- Common Reasons for Termination
SELECT count(TERMINATIONTYPE) AS TERMINATIONREASON, terminationtype from EMPLOYEES
GROUP BY TERMINATIONTYPE
HAVING TERMINATIONTYPE IS NOT NULL;

--Correlation Between Demographics and Satisfaction
SELECT E.GENDERCODE,E.RACEDESC,E.MARITALDESC, ROUND(AVG(EN.SATISFACTION_SCORE),2) AS AVG_SAT FROM EMPLOYEES E INNER JOIN EMPLOYEE_ENGAGEMENT_SURVEY as EN ON E.EMPID=EN.EMPLOYEE_ID
GROUP BY E.GENDERCODE,E.RACEDESC,E.MARITALDESC

--Training Programs with Highest Impact on Performance Improvement

SELECT E.TRAINING_PROGRAM_NAME, AVG(EMPLOYEERATING) FROM TRAINING_DEV E JOIN EMPLOYEES EM ON E.EMPLOYEE_ID=EM.EMPID
GROUP BY E.TRAINING_PROGRAM_NAME;

--Distribution of Employee Ratings Across Business Units
SELECT BUSINESSUNIT,AVG(EMPLOYEERATING) AS AVG_RATING FROM EMPLOYEES
GROUP BY BUSINESSUNIT;

--. Employee Engagement by Job Function
SELECT e.JOBFUNCTIONDESCRIPTION, AVG(s.ENGAGEMENT_SCORE) AS Avg_Engagement_Score
FROM SQL_PROJECT.PUBLIC.EMPLOYEES e
JOIN SQL_PROJECT.PUBLIC.EMPLOYEE_ENGAGEMENT_SURVEY s ON e.EMPID = s.EMPLOYEE_ID
GROUP BY e.JOBFUNCTIONDESCRIPTION
ORDER BY Avg_Engagement_Score DESC;

--Employees with the Highest Training Costs

SELECT E.EMPLOYEE_ID,E.TRAINING_COST, CONCAT(EM.FIRSTNAME,' ',EM.LASTNAME) as EMP_NAME FROM TRAINING_DEV E JOIN EMPLOYEES EM ON E.EMPLOYEE_ID=EM.EMPID
ORDER BY TRAINING_COST DESC
LIMIT 10;

--Average Satisfaction Score by Job Title

SELECT E.TITLE, AVG(SAT.SATISFACTION_SCORE) AS AVG_SAT FROM EMPLOYEES E JOIN EMPLOYEE_ENGAGEMENT_SURVEY SAT ON E.EMPID=SAT.EMPLOYEE_ID
GROUP BY E.TITLE
ORDER BY AVG_SAT DESC;

--Average Training Cost per Department

SELECT  AVG(T.TRAINING_COST) as AVG_COST, E.DIVISION FROM TRAINING_DEV AS T JOIN EMPLOYEES AS E ON T.EMPLOYEE_ID=E.EMPID
GROUP BY E.DIVISION;


--Correlation Between Engagement Score and Performance Score
SELECT e.EMPID, e.FIRSTNAME, e.LASTNAME, s.ENGAGEMENT_SCORE, e.PERFORMANCESCORE
FROM SQL_PROJECT.PUBLIC.EMPLOYEES e
JOIN SQL_PROJECT.PUBLIC.EMPLOYEE_ENGAGEMENT_SURVEY s ON e.EMPID = s.EMPLOYEE_ID
WHERE e.PERFORMANCESCORE IS NOT NULL
ORDER BY s.ENGAGEMENT_SCORE DESC;
